SINTERWEB/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login, logout

from abonado.views import *
from caja.views import *
from servicio.views import * 

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #----------------------------SISTEMA LOGIN----------------------------#
    url(r'^$', login, {'template_name': 'front.html', }, name="login"),
    url(r'^logout/$', logout, {'template_name': 'front.html', }, name='logout'),
    url(r'^signup/$', 'front.views.signup', name='signup'),
    #---------------------------------------------------------------------#


    #--------------------------------FRONT--------------------------------#
    url(r'^home/$','front.views.home', name="home"),
    url(r'^rg_abonado/$', 'abonado.views.rg_abonado', name='rg_abonado'),
    url(r'^rg_caja/$', CajaView.as_view(), name="rg_caja"),
    url(r'^rg_servicio/$', ServView.as_view(), name="rg_servicio"),
    #---------------------------------------------------------------------#

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abonado/models.py
from __future__ import unicode_literals

from django.db import models
# Create your models here.

class abonado(models.Model):
	cedula = models.CharField(max_length=10, null=True, blank=True)
	num_abonado = models.IntegerField(primary_key=True)
	nombre_abo1 = models.CharField(max_length=30, null=True, blank=True)
	nombre_abo2 = models.CharField(max_length=30)
	apellido_abo1 = models.CharField(max_length=30, null=True, blank=True)
	apellido_abo2 = models.CharField(max_length=30)
	direccion_abo = models.TextField(max_length=500, null=True, blank=True)

	def __unicode__(self):
		Dato ="%i"%(self.num_abonado)
		return Dato

caja/models.py
from __future__ import unicode_literals

from django.db import models
from abonado.models import *
# Create your models here.

class caja(models.Model):
	serial = models.CharField(max_length=40, null=True, blank=True, unique=True)
	num_abonado2 = models.ForeignKey(abonado, on_delete=models.CASCADE)

	def __unicode__(self):
		Dato ="%s"%(self.serial)
		return Dato

front/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

# Create your models here.

class login(models.Model):
	username = models.CharField(max_length=25, null=True)
	password = models.CharField(max_length=25, null=True)
	email = models.CharField(max_length=25, null=True)
	first_name = models.CharField(max_length=25, null=True)
	last_name = models.CharField(max_length=25, null=True)

	def __unicode__(self):
		return username

servicio/models.py
from __future__ import unicode_literals

from django.db import models

from caja.models import *
from abonado.models import abonado
# Create your models here.

class servicio(models.Model):
	cedula2 = models.CharField(max_length=10, null=True, blank=True)
	num_abonado3 = models.ForeignKey(abonado, on_delete=models.CASCADE)
	nombre_abo_serv1 = models.CharField(max_length=30, null=True, blank=True)
	nombre_abo_serv2 = models.CharField(max_length=30)
	apellido_abo_serv1 = models.CharField(max_length=30, null=True, blank=True)
	apellido_abo_serv2 = models.CharField(max_length=30)
	direccion_abo_serv = models.TextField(max_length=500, null=True, blank=True)
	serial2 = models.ForeignKey(caja, on_delete=models.CASCADE)
	descripcion = models.TextField(max_length=500, null=True, blank=True)

	def __unicode__(self):
		Dato ="%s"%(self.cedula2)
		return Dato

front/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
 
 
class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {'password': forms.PasswordInput()}

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Current Password', 'autocomplete': 'off'}))

    new_password = forms.CharField(
        min_length=6,
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'New Password', 'autocomplete': 'off'}))

    confirm_password = forms.CharField(
        min_length=6,
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirm New Password', 'autocomplete': 'off'}))

front/views.py
from django.template import Context
from django.template.loader import get_template
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.utils import timezone

from front.forms import *

# Create your views here.

#-----------NUEVOS USUARIOS--------------------------------------------------------------#

@login_required()
def signup(request):
    if request.method == 'POST':  # If the form has been submitted...
        form = SignUpForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
 
            # Process the data in form.cleaned_data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
 
            # At this point, user is a User object that has already been saved
            # to the database. You can continue to change its attributes
            # if you want to change other fields.
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
 
            # Save new user attributes
            user.save()
            return HttpResponseRedirect('/')    
            #return HttpResponseRedirect(reverse('main.html'))  # Redirect after POST
    else:
        form = SignUpForm()
 
    data = {
        'form': form,
    }
    return render_to_response('signup.html', data, context_instance=RequestContext(request))
#-----------------------------------------------------------------------------------------#


#----------HOME---------------------------------------------------------------------------#
def home(request):
    return render_to_response('home.html', {'user': request.user},
    context_instance=RequestContext(request))
#-----------------------------------------------------------------------------------------#    

templates/rg_abonado.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
    <link rel="shortcut icon" href="/static/img/inter.ico">

    <link rel="stylesheet" href="/static/css/fuente.css">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" type="text/css" href="/static/css/registro.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <title>| SINTERWEB |</title>
</head>
<body>
    <div class="menu">
    {% block usertools %}
        <ul>
            <li><a href="/home/"><span class="fa fa-home"></span>Inicio</a></li>
            <li><a href="#"><span class="fa fa-book"></span>Registro <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="/rg_abonado/"><span class="fa fa-share"></span>Abonado</a></li>
                    <li><a href="/rg_caja/"><span class="fa fa-share"></span>Cajas</a></li>
                    <li><a href="/rg_servicio/"><span class="fa fa-share"></span>Servicios</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-line-chart"></span>Status <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total Cajas</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-file-pdf-o"></span>Reportes <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total De Cajas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cont. Reclamos</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-support"></span>Ayuda <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    {% if user.is_superuser %}
                    <li><a href="/signup/"><span class="fa fa-share"></span>Nuevos Usuarios</a></li>
                    {% endif %}
                    <li><a href="#"><span class="fa fa-share"></span>Manual Usuarios</a></li>
                </ul>
            </li>
            <li><a href="/logout/"><span class="fa fa-mail-reply-all"></span>Salir</a></li>
        </ul>
    {% endblock %}    
    </div>
    
    <div class="contenedor">
            <div class="input-group">
                <h2>REGISTRO ABONADO <span class="fa fa-user"></span></h2>
            </div>
            {% block content %}
            <form class="formulario" name="formulario_registro" method="GET">{% csrf_token %}
                <div>
                    <div class="input-group">
                        <input type="text" id="id_cedula" name="cedula" placeholder="Cédula V-12456763 (*)">
                        <input type="text" id="id_num_abonado" name="num_abonado" placeholder="N° Abonado (*)">
                    </div>
                    <div class="input-group">
                        <input type="text" id="id_nombre_abo1" name="nombre_abo1" placeholder="Primer Nombre (*)">
                        <input type="text" id="id_nombre_abo2" name="nombre_abo2" placeholder="Segundo Nombre">
                    </div>
                    <div class="input-group">
                        <input type="text" id="id_apellido_abo1" name="apellido_abo1" placeholder="Primer Apellido (*)">
                        <input type="text" id="id_apellido_abo2" name="apellido_abo2" placeholder="Segundo Apellido">
                    </div>
                    <div class="input-group">
                        <textarea type="text" id="id_direccion_abo" name="direccion_abo" placeholder="Dirección (*)"></textarea>
                    </div>                        
                    <div class="input-group">
                        <input type="submit" value="GUARDAR" onclick='alert("Guardado Exitosamente")'>
                        <input type="hidden" name="next" value="{{ next }}">
                        <input class="btn__reset" type="reset" value="LIMPIAR">
                    </div>    
                </div>
            </form>
        {% endblock  %}
    </div>

    <footer class="footer">
        <div class="social">
            <a href="#" class="icon-facebook"></a>
            <a href="#" class="icon-twitter"></a>
            <a href="#" class="icon-instagram"></a>
            <a href="#" class="icon-google-plus"></a>
            <a href="#" class="icon-github"></a>
        </div>
        <p class="copy">| &copy;EliDjangoDev 2017 | Programadores U.P.T.P JJ "Montilla" | Todos los derecho reservador |</p>
    </footer>
</body>
</html>

templates/rg_caja.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
    <link rel="shortcut icon" href="/static/img/inter.ico">

    <link rel="stylesheet" href="/static/css/fuente.css">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" type="text/css" href="/static/css/caja.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <title>| SINTERWEB |</title>
</head>
<body>
    <div class="menu">
    {% block usertools %}
        <ul>
            <li><a href="/home/"><span class="fa fa-home"></span>Inicio</a></li>
            <li><a href="#"><span class="fa fa-book"></span>Registro <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="/rg_abonado/"><span class="fa fa-share"></span>Abonado</a></li>
                    <li><a href="/rg_caja/"><span class="fa fa-share"></span>Cajas</a></li>
                    <li><a href="/rg_servicio/"><span class="fa fa-share"></span>Servicios</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-line-chart"></span>Status <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total Cajas</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-file-pdf-o"></span>Reportes <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total De Cajas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cont. Reclamos</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-support"></span>Ayuda <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    {% if user.is_superuser %}
                    <li><a href="/signup/"><span class="fa fa-share"></span>Nuevos Usuarios</a></li>
                    {% endif %}
                    <li><a href="#"><span class="fa fa-share"></span>Manual Usuarios</a></li>
                </ul>
            </li>
            <li><a href="/logout/"><span class="fa fa-mail-reply-all"></span>Salir</a></li>
        </ul>
    {% endblock %}    
    </div>
    
    <div class="contenedor">
            <div class="input-group">
                <h2>REGISTRO CAJAS <span class="fa fa-archive"></span></h2>
            </div>
            <form class="formulario" name="formulario_registro" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div>
                    <div class="input-group">
                        <input type="text" id="id_serial" name="serial" placeholder="Serial (*)" required>
                        <select name="num_abonado2" id="id_num_abonado2" required>
                            <option value="">Seleccione el N° Abonado (*)</option>
                            {% for abonado in data %}
                            <option value="{{ abonado.pk }}">{{ abonado.num_abonado }}</option>
                            {% endfor %}
                        </select>                        
                    </div>
                    <div class="input-group">
                        <input type="submit" value="GUARDAR" onclick='alert("Guardado Exitosamente")'>
                        <input type="hidden" name="next" value="{{ next }}">
                        <input class="btn__reset" type="reset" value="LIMPIAR">
                    </div>   
                </div>
            </form>
    </div>

    <footer class="footer">
        <div class="social">
            <a href="#" class="icon-facebook"></a>
            <a href="#" class="icon-twitter"></a>
            <a href="#" class="icon-instagram"></a>
            <a href="#" class="icon-google-plus"></a>
            <a href="#" class="icon-github"></a>
        </div>
        <p class="copy">| &copy;EliDjangoDev 2017 | Programadores U.P.T.P JJ "Montilla" | Todos los derecho reservador |</p>
    </footer>
</body>
</html>

templates/rg_servicio.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
    <link rel="shortcut icon" href="/static/img/inter.ico">

    <link rel="stylesheet" href="/static/css/fuente.css">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" type="text/css" href="/static/css/servicio.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <title>| SINTERWEB |</title>
</head>
<body>
    <div class="menu">
    {% block usertools %}
        <ul>
            <li><a href="/home/"><span class="fa fa-home"></span>Inicio</a></li>
            <li><a href="#"><span class="fa fa-book"></span>Registro <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="/rg_abonado/"><span class="fa fa-share"></span>Abonado</a></li>
                    <li><a href="/rg_caja/"><span class="fa fa-share"></span>Cajas</a></li>
                    <li><a href="/rg_servicio/"><span class="fa fa-share"></span>Servicios</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-line-chart"></span>Status <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total Cajas</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-file-pdf-o"></span>Reportes <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total De Cajas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cont. Reclamos</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-support"></span>Ayuda <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    {% if user.is_superuser %}
                    <li><a href="/signup/"><span class="fa fa-share"></span>Nuevos Usuarios</a></li>
                    {% endif %}
                    <li><a href="#"><span class="fa fa-share"></span>Manual Usuarios</a></li>
                </ul>
            </li>
            <li><a href="/logout/"><span class="fa fa-mail-reply-all"></span>Salir</a></li>
        </ul>
    {% endblock %}    
    </div>
    
    <div class="contenedor">
            <div class="input-group">
                <h2>SERVICIOS <span class="fa fa-commenting"></span></h2>
            </div>
            <br>
            <form class="formulario" name="formulario_registro" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div>
                    <div class="input-group">
                        <input type="text" id="id_cedula2" name="cedula2" placeholder="Cédula V-12456763 (*)">
                        <select name="num_abonado3" id="id_num_abonado3">
                            <option value="">Seleccione el N° Abonado (*)</option>
                            {% for abonado in data %}
                            <option value="{{ abonado.pk }}">{{ abonado.num_abonado }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-group">
                        <input type="text" id="id_nombre_abo_serv1" name="nombre_abo_serv1" placeholder="Primer Nombre (*)">
                        <input type="text" id="id_nombre_abo_serv2" name="nombre_abo_serv2" placeholder="Segundo Nombre">
                    </div>
                    <div class="input-group">
                        <input type="text" id="id_apellido_abo_serv1" name="apellido_abo_serv1" placeholder="Primer Apellido (*)">
                        <input type="text" id="id_apellido_abo_serv2" name="apellido_abo_serv2" placeholder="Segundo Apellido">
                    </div>
                    <div class="input-group">
                        <textarea type="text" id="id_direccion_abo_serv" name="direccion_abo_serv" placeholder="Dirección (*)"></textarea>
                    </div>
                    <div class="input-group">
                        <select class="input-100" name="serial2" id="id_serial2">
                            <option value="">Seleccione el Serial (*)</option>
                            {% for caja in data %}
                            <option value="{{ caja.pk }}">{{ caja.serial }}</option>
                            {% endfor %}
                        </select>
                    </div> 
                    <div class="input-group">
                        <textarea type="text" id="id_descripcion" name="descripcion" placeholder="Descripción (*)"></textarea>
                    </div>                      
                    <div class="input-group">
                        <input type="submit" value="GUARDAR" onclick='alert("Guardado Exitosamente")'>
                        <input type="hidden" name="next" value="{{ next }}">
                        <input class="btn__reset" type="reset" value="LIMPIAR">
                    </div>    
                </div>
            </form>
            <br><br>
            <p>_</p>
    </div>

    <footer class="footer">
        <div class="social">
            <a href="#" class="icon-facebook"></a>
            <a href="#" class="icon-twitter"></a>
            <a href="#" class="icon-instagram"></a>
            <a href="#" class="icon-google-plus"></a>
            <a href="#" class="icon-github"></a>
        </div>
        <p class="copy">| &copy;EliDjangoDev 2017 | Programadores U.P.T.P JJ "Montilla" | Todos los derecho reservador |</p>
    </footer>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
 
    <link rel="shortcut icon" href="/static/img/inter.ico">

    <link rel="stylesheet" href="/static/css/fuente.css">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" type="text/css" href="/static/css/signup.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <title>| SINTERWEB |</title>
</head>
<body>
    <div class="menu">
    {% block usertools %}
        <ul>
            <li><a href="/home/"><span class="fa fa-home"></span>Inicio</a></li>
            <li><a href="#"><span class="fa fa-book"></span>Registro <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="/rg_abonado/"><span class="fa fa-share"></span>Abonado</a></li>
                    <li><a href="/rg_caja/"><span class="fa fa-share"></span>Cajas</a></li>
                    <li><a href="/rg_servicio/"><span class="fa fa-share"></span>Servicios</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-line-chart"></span>Status <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total Cajas</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-file-pdf-o"></span>Reportes <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Donadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparadas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cajas Reparables</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Status Reclamos</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Total De Cajas</a></li>
                    <li><a href="#"><span class="fa fa-share"></span>Cont. Reclamos</a></li>
                </ul>
            </li>
            <li><a href="#"><span class="fa fa-support"></span>Ayuda <p class="fa fa-ellipsis-v"></p></a>
                <ul>
                    {% if user.is_superuser %}
                    <li><a href="/signup/"><span class="fa fa-share"></span>Nuevos Usuarios</a></li>
                    {% endif %}
                    <li><a href="#"><span class="fa fa-share"></span>Manual Usuarios</a></li>
                </ul>
            </li>
            <li><a href="/logout/"><span class="fa fa-mail-reply-all"></span>Salir</a></li>
        </ul>
    {% endblock %}    
    </div>
    
    <div class="contenedor">
            <div class="input-group">
                <h2>NUEVOS USUARIOS <span class="fa fa-users"></span></h2>
            </div>
            <br>
            <form action="{% url 'signup' %}" class="formulario" name="formulario_registro" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div>
                    <div class="input-group">
                        <input maxlength="30" type="text" id="id_first_name" name="first_name" placeholder="Nombre" required>
                        <input maxlength="30" type="text" id="id_last_name" name="last_name" placeholder="Apellido" required>
                    </div>
                    <div class="input-group">
                        <input maxlength="254" type="email" id="id_email" name="email" placeholder="Ejemplo@email.com" class="input-100" required>
                    </div>
                    <div class="input-group">
                        <input maxlength="30" type="text" id="id_username" name="username" placeholder="Usuario" required>
                        <input maxlength="20" type="password" id="id_password" name="password" placeholder="Contraseña" required>
                    </div>                    
                    <div class="input-group">
                        <input type="submit" value="GUARDAR" onclick='alert("Guardado Exitosamente")'>
                        <input type="hidden" name="next" value="{{ next }}">
                        <input class="btn__reset" type="reset" value="LIMPIAR">
                    </div>
                </div>
            </form>
            {% if form.errors %}<p>{{ form.errors }}</p>{% endif %}
            <br><br>
    </div>

    <footer class="footer">
        <div class="social">
            <a href="#" class="icon-facebook"></a>
            <a href="#" class="icon-twitter"></a>
            <a href="#" class="icon-instagram"></a>
            <a href="#" class="icon-google-plus"></a>
            <a href="#" class="icon-github"></a>
        </div>
        <p class="copy">| &copy;EliDjangoDev 2017 | Programadores U.P.T.P JJ "Montilla" | Todos los derecho reservador |</p>
    </footer>
</body>
</html>